from typing import Annotated, Any, Dict, List, Optional
from typing_extensions import TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph import MessagesState, add_messages


def add_artifacts(left: List["Artifact"], right: List["Artifact"]) -> List["Artifact"]:
    """
    Reducer function to accumulate artifacts.

    Appends new artifacts to the existing list instead of replacing.

    Args:
        left: Existing artifacts
        right: New artifacts to add

    Returns:
        Combined list of artifacts
    """
    if not left:
        return right
    if not right:
        return left
    return left + right


def update_analysis_steps(left: List["AnalysisStep"], right: List["AnalysisStep"]) -> List["AnalysisStep"]:
    """
    Reducer function to update analysis steps.

    Merges step updates based on order. If a step with the same order exists,
    it gets updated; otherwise, new steps are appended.

    Args:
        left: Existing steps
        right: New or updated steps

    Returns:
        Updated list of steps
    """
    if not left:
        return right
    if not right:
        return left

    # Create a dictionary from left steps using order as key
    steps_dict = {step.get("order"): step for step in left}

    # Update or add steps from right
    for step in right:
        order = step.get("order")
        if order is not None:
            steps_dict[order] = step

    # Return sorted by order
    return sorted(steps_dict.values(), key=lambda x: x.get("order", 0))


class RouterDecision(TypedDict, total=False):
    """
    Structure for router decisions.

    Attributes:
        route: Where to route ("chat", "analysis", "analysis_followup")
        reasoning: Why this route was chosen
    """
    route: str  # "chat", "analysis", "analysis_followup"
    reasoning: str


class SupervisorDecision(TypedDict, total=False):
    """
    Structure for supervisor decisions.

    Attributes:
        needs_analysis: Whether new code execution is needed
        reasoning: Why this decision was made
    """
    needs_analysis: bool
    reasoning: str


class Artifact(TypedDict, total=False):
    """
    Structure for storing analysis artifacts (plots, tables, insights).

    Attributes:
        type: Type of artifact ('plot', 'table', 'insight', 'code')
        content: The actual content (file path for plots, markdown for tables, text for insights)
        description: Human-readable description of the artifact
        timestamp: When the artifact was created
    """
    type: str
    content: str
    description: str
    timestamp: str


class AnalysisStep(TypedDict, total=False):
    """
    Structure for tracking individual steps in the analysis plan.

    Attributes:
        description: What needs to be done in this step
        status: Current status ('pending', 'in_progress', 'completed', 'skipped')
        order: Order of execution (1, 2, 3, ...)
        result_summary: Brief summary after completion
    """
    description: str
    status: str
    order: int
    assigned_agent: str
    result_summary: str


class UnifiedAnalysisState(MessagesState):
    """
    State for the Unified Analysis Agent workflow.

    Supports multiple asset types: Excel, Documents, PowerPoint, etc.
    Extends MessagesState to automatically handle message history with the
    add_messages reducer, while adding custom fields for analysis.

    Attributes:
        messages: List of messages (inherited) - user queries, plans, final analysis
        file_path: Path to the file being analyzed (any supported type)
        asset_type: Type of asset ('excel', 'document', 'powerpoint')
        excel_file_path: DEPRECATED - Use file_path instead. Kept for backward compatibility.
        data_context: Structured dict with file info and description from Inspector
        route_decision: Router's decision on where to route the query
        supervisor_decision: Supervisor's decision on whether analysis is needed
        analysis_plan: Detailed plan of action generated by Planning Node
        user_query: Extracted user query to pass to coding subgraph
        code_iterations: Number of code execution attempts (defaults to 0)
        execution_result: Result from the coding agent's execution (defaults to empty)
        final_analysis: Final analysis output from the coding agent (defaults to empty)
        artifacts: List of analysis artifacts (plots, tables, insights) accumulated
        analysis_steps: Structured list of analysis steps with status tracking
    """

    # New unified fields
    file_path: Optional[str]  # DEPRECATED - use assets list
    asset_type: Optional[str]  # DEPRECATED - use assets list
    kbid: Optional[str]  # DEPRECATED - use assets list
    
    # Multi-asset support
    assets: Optional[List[Dict[str, Any]]]  # List of {path, type, kbid, id}
    data_contexts: Optional[Dict[str, Dict[str, Any]]]  # Map of asset_id -> context
    
    # Backward compatibility - will be synced with file_path for Excel files
    excel_file_path: Optional[str]  # DEPRECATED - use assets
    
    data_context: Optional[Dict[str, Any]]  # DEPRECATED - use data_contexts
    route_decision: Optional[RouterDecision]  # Router's classification
    supervisor_decision: Optional[SupervisorDecision]  # Supervisor's needs_analysis decision
    analysis_plan: Optional[str]
    user_query: Optional[str]  # Extracted user query for coding subgraph
    code_iterations: int
    execution_result: Optional[str]
    final_analysis: Optional[str]
    artifacts: Annotated[List[Artifact], add_artifacts]
    analysis_steps: Annotated[List[AnalysisStep], update_analysis_steps]
    active_step_index: int


# Backward compatibility alias
ExcelAnalysisState = UnifiedAnalysisState


class CodingSubgraphInput(TypedDict, total=False):
    """
    Input state for the Coding Agent Subgraph.

    This defines what data flows FROM parent TO subgraph.
    Intentionally excludes messages to prevent parent messages from entering subgraph.

    Attributes:
        file_path: Path to the file being analyzed (any supported type)
        asset_type: Type of asset ('excel', 'document', 'powerpoint')
        excel_file_path: DEPRECATED - Use file_path. Kept for backward compatibility.
        data_context: Structured dict with file info and description
        analysis_plan: Detailed plan of action to execute
        user_query: The original user query (extracted from parent messages)
        analysis_steps: Structured list of analysis steps with status tracking
    """
    file_path: str  # DEPRECATED
    asset_type: str  # DEPRECATED
    kbid: str  # DEPRECATED
    excel_file_path: str  # DEPRECATED
    assets: List[Dict[str, Any]]
    data_contexts: Dict[str, Dict[str, Any]]
    data_context: Dict[str, Any]  # DEPRECATED
    analysis_plan: str
    user_query: str
    analysis_steps: List[AnalysisStep]
    active_step_index: int


class CodingSubgraphOutput(TypedDict, total=False):
    """
    Output state for the Coding Agent Subgraph.

    This defines what data flows FROM subgraph TO parent.
    Only includes the final analysis message and artifacts, not tool calls.

    Attributes:
        messages: Only the final analysis message (clean, no tool calls)
        artifacts: List of analysis artifacts (plots, tables, insights)
        analysis_steps: Updated analysis steps with completion status
        final_analysis: Final analysis text
    """
    messages: List
    artifacts: List[Artifact]
    analysis_steps: List[AnalysisStep]
    final_analysis: str


class CodingSubgraphState(TypedDict, total=False):
    """
    Internal state for the Coding Agent Subgraph - ISOLATED from parent.

    This state does NOT extend MessagesState to prevent automatic message merging.
    Messages are handled explicitly with add_messages reducer only within subgraph.
    This ensures tool calls and internal messages stay INSIDE the subgraph.

    Supports any asset type (Excel, Document, PowerPoint).

    Attributes:
        messages: List of internal messages (tool calls, etc.) - NOT merged with parent
        file_path: Path to the file being analyzed (any supported type)
        asset_type: Type of asset ('excel', 'document', 'powerpoint')
        excel_file_path: DEPRECATED - Use file_path. Kept for backward compatibility.
        data_context: Structured dict with file info and description
        analysis_plan: Detailed plan of action to execute
        user_query: The original user query
        code_iterations: Number of code execution attempts (defaults to 0)
        final_analysis: Final analysis output (defaults to empty)
        artifacts: List of analysis artifacts generated during code execution
        analysis_steps: Structured list of analysis steps with status tracking
    """

    messages: Annotated[List[BaseMessage], add_messages]
    file_path: str  # DEPRECATED
    asset_type: str  # DEPRECATED
    kbid: str  # DEPRECATED
    excel_file_path: str  # DEPRECATED
    assets: List[Dict[str, Any]]
    data_contexts: Dict[str, Dict[str, Any]]
    data_context: Dict[str, Any]  # DEPRECATED
    analysis_plan: str
    user_query: str
    code_iterations: int
    final_analysis: str
    artifacts: Annotated[List[Artifact], add_artifacts]
    analysis_steps: Annotated[List[AnalysisStep], update_analysis_steps]
    active_step_index: int
